# Generated by Django 4.1.5 on 2023-02-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_qrcode_id_in_electron_alter_qrcode_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='id_in_electron',
            field=models.IntegerField(unique=True, verbose_name='id счетчика'),
        ),
    ]
